config/routes.rb
Rails.application.routes.draw do
  resources :friendships, only: [:create, :update, :destroy]

  authenticated :user do
    root to: 'profiles#show', as: :authenticated_root
  end

  root to: 'welcome#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :books
  resources :users do
    resources :book_copies do
      resources :rental_books
    end
    resource :profile
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: [:edit, :new, :update]

  def show
    @users = User.all
    @copies = current_user.available_books_to_borrow
    @borrowed_books = current_user.borrowed_books
    @borrow_books = current_user.borrow_books
  end

  def edit
  end

  def new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to user_profile_path(current_user), notice: 'User profile was successfully created.'
    else
      render :new
    end
  end

  def update
    if @profile.update_attributes(profile_params)
      redirect_to user_profile_path(current_user), notice: 'User profile was successfully updated.'
    else
      render :new
    end
  end

  # def create
  #   @profile = Profile.new(profile_params)
  #   if @profile.save
  #     redirect_to user_profile_path(resource)
  #   else
  #     render :new
  #   end
  # end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:name, :avatar)
  end
end

app/views/profiles/_form.haml
.form
  %h2
    Edit profile
  = simple_form_for @profile, url: user_profile_path(current_user) do |f|
    .form-inputs
      = f.input :name
      .custom-file-upload
        = f.input :avatar, as: :file
        Avatar upload
    .form-actions
      = f.button :submit

app/views/profiles/edit.haml
= render 'form'

app/views/profiles/new.haml
= render 'form'

app/views/profiles/show.haml
.main
  %section.friends
    - if current_user.requested_friendships.any? || current_user.pending_friends.any?
      %h3
        pending friends
      .list
        %ul
          - current_user.requested_friendships.each do |friend|
            %li
              - if friend.profile.avatar.present?
                .show-profile-avatar-wrapper
                  = image_tag friend.profile.avatar, class: "show-profile-avatar"
              - else
                %svg
                  %circle{ style: "fill: ##{SecureRandom.hex(3)}"}
              = friend.name
              = link_to "accept",  friendship_path(id: friend.id), method: :put
              = link_to "decline", friendship_path(id: friend.id), method: :delete
        %ul
          - current_user.pending_friends.each do |friend|
            %li
              - if friend.profile.avatar.present?
                .show-profile-avatar-wrapper
                  = image_tag friend.profile.avatar, class: "show-profile-avatar"
              - else
                %svg
                  %circle{ style: "fill: ##{SecureRandom.hex(3)}"}
              = friend.name

    - if current_user.friends.present?
      %h3
        friends
      .list
        %ul
          - current_user.friends.each do |friend|
            %li
              - if friend.profile.avatar.present?
                .show-profile-avatar-wrapper
                  = image_tag friend.profile.avatar, class: "show-profile-avatar"
              - else
                %svg
                  %circle{ style: "fill: ##{SecureRandom.hex(3)}"}
              = friend.name

    %h3
      available friends
    .list
      %ul
        - current_user.available_friends.each do |friend|
          %li
            - if friend.profile.avatar.present?
              .show-profile-avatar-wrapper
                = image_tag friend.profile.avatar, class: "show-profile-avatar"
            - else
              %svg
                %circle{ style: "fill: ##{SecureRandom.hex(3)}"}
            = friend.name
            = link_to "add friend", friendships_path(friend_id: friend.id), method: :post
    %h3
      friends' books
    .booklist
      %ul
        - @copies.each do |copy|
          %li
            %svg
              %rect{ style: "fill: ##{SecureRandom.hex(3)}"}
            .booktitle
              = copy.book.title
            .author
              = copy.book.author
            = link_to "Borrow book from #{copy.owner.name}", user_book_copy_rental_books_path(current_user, copy), method: :post

  %section.books
    = image_tag current_user.profile.avatar

    %h3
      books on home shelf
    = link_to "add book", new_book_path
    .booklist
      - if current_user.available_copies.present?
        - current_user.available_copies.each do |copy|
          %svg
            %rect{ style: "fill: ##{SecureRandom.hex(3)}"}
          .booktitle
            = copy.book.title
          .author
            = copy.book.author
      - else
        .alert
          your shelf is empty! :(

  %section.status
    %h3
      borrowed books
    .booklist
      - @borrowed_books.each do |copy|
        %svg
          %rect{ style: "fill: ##{SecureRandom.hex(3)}"}
        .booktitle
          = copy.book.title
        .author
          = copy.book.author
          from
          = copy.owner.name

      - @borrow_books.each do |copy|
        %svg
          %rect{ style: "fill: ##{SecureRandom.hex(3)}"}
        .booktitle
          = "#{copy.book.title} (pending)"
        .author
          = copy.book.author
          from
          = copy.owner.name

    %h3
      lent books
    .booklist
      - current_user.lend_books.each do |copy|
        %svg
          %rect{ style: "fill: ##{SecureRandom.hex(3)}"}
        .booktitle
          = "#{copy.book.title} (pending)"
        .author
          = copy.book.author
        = link_to "lend", user_book_copy_rental_book_path(current_user, copy, copy.rental_books.last), method: :put
        = link_to "dismiss", user_book_copy_rental_book_path(current_user, copy, copy.rental_books.last), method: :delete
        to
        = copy.rental_books.last.user.name
      - current_user.lent_books.each do |copy|
        %svg
          %rect{ style: "fill: ##{SecureRandom.hex(3)}"}
        .booktitle
          = copy.book.title
        .author
          = copy.book.author
        to
        = copy.rental_books.last.user.name