config/routes.rb
Rails.application.routes.draw do
  resources :friendships, only: [:create, :update, :destroy]

  authenticated :user do
    root to: 'profiles#show', as: :authenticated_root
  end

  root to: 'welcome#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :books
  resources :users do
    resources :book_copies do
      resources :rental_books
    end
    resource :profile
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title
      HomeShelf
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  %body
    .navbar-text
      .title
        - if user_signed_in?
          = link_to "HomeShelf", user_profile_path(current_user)
        - else
          HomeShelf
      .alert
        - if notice
          = notice
        - if alert
          = alert
      - if user_signed_in?
        .user
          - if current_user.profile.name.present?
            = current_user.profile.name
            's shelf
          - else
            = current_user.email
        = link_to "Log out", destroy_user_session_path, method: :delete, :class => 'navbar-link'
        = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'

      - else
        = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
        = link_to "Log in", new_user_session_path, :class => 'navbar-link'
    = yield